USE highqhomes;

INSERT INTO `page_sections` (`page_key`,`section_key`,`title`,`subtitle`,`content`,`data`,`image_url`,`sort_order`) VALUES
('about','hero','Who We Are','Built on integrity. Delivered with precision.','Premium construction and architecture across Puntland — broad vision, honest service, and great value.',NULL,'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1920&q=80',1),
('about','history','Our History','The HighQ Homes story','HighQ Homes was founded in Garowe with a clear purpose — deliver world-class residential and commercial construction with honest service, broad vision, and great value. From our first projects to integrated design-build delivery today, we have grown by keeping quality, transparency, and client trust at the center of every build.',JSON_OBJECT('facts',JSON_ARRAY(JSON_OBJECT('label','Founded','value','2020'),JSON_OBJECT('label','Headquarters','value','Garowe, Puntland'),JSON_OBJECT('label','Focus','value','Residential & Commercial')), 'timeline', JSON_ARRAY(JSON_OBJECT('year','2020','text','HighQ Homes established in Garowe with a mission to raise construction standards across Puntland.'),JSON_OBJECT('year','2021','text','First residential and commercial projects delivered with structured quality control.'),JSON_OBJECT('year','2023','text','Expanded integrated design, construction, and finishing services under one accountable team.'),JSON_OBJECT('year','Today','text','Trusted partner for premium builds — from first consultation to final handover.'))),'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80',2),
('about','values','Our Values','What guides every project','',JSON_ARRAY(JSON_OBJECT('icon','bi-shield-check','title','Integrity First','text','Honest timelines, transparent pricing, and accountable communication at every stage.'),JSON_OBJECT('icon','bi-gem','title','Premium Quality','text','Materials and workmanship held to standards you can see and measure.'),JSON_OBJECT('icon','bi-people','title','Client Partnership','text','Responsive support before, during, and after project handover.'),JSON_OBJECT('icon','bi-compass','title','Local Expertise','text','Deep knowledge of Puntland sites, regulations, and community development needs.')),NULL,3),
('about','process','How We Work','Simple steps, clear delivery','A structured path that keeps your project transparent, controlled, and on schedule.',JSON_ARRAY(JSON_OBJECT('num','01','title','Consultation','text','We learn your goals, site conditions, and budget expectations.'),JSON_OBJECT('num','02','title','Planning','text','Drawings, materials, and a milestone schedule you can track.'),JSON_OBJECT('num','03','title','Construction','text','Disciplined site execution with quality checks at every phase.'),JSON_OBJECT('num','04','title','Handover','text','Final walkthrough, documentation, and after-care support.')),NULL,4)
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `subtitle` = VALUES(`subtitle`),
  `content` = VALUES(`content`),
  `data` = VALUES(`data`),
  `image_url` = VALUES(`image_url`),
  `sort_order` = VALUES(`sort_order`);
